{{- if .Values.namespace.enabled -}}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

{{- end}}

  