apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ .Values.trigramme }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.application_name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

